### ISSUE TITLE
Build Another Version With Different Program Flow?

### ISSUE THREAD

**Issue by EAWF** [Septem151/Deriver-Tool#1]
Any way you can take time to build another version that follows the program flow below:

Accept as input an account-level extended public key and an Index
	IF extended key is BIP44 (xpub)
		Return P2PKH address at given index
	ELSE IF extended key is BIP49 (ypub)
		Return P2SH-P2WPKH address at given index
	ELSE IF extended key is BIP84 (zpub)
		Return P2WPKH address at given index

Going to assume that it's not simple, but, hoping that it is.

Also would be nice if it was possible to port this module  over to JavaScript?

**Comment by Septem151** [comment]
Do you still want the program to be an interactive standalone CLI, or be made into an importable library (or both)?

Changing the program flow wouldn't be an issue. I could make a JavaScript port but it would rely on other bitcoin/cryptographic dependencies.

**Comment by EAWF** [comment]
I'm not sure if the CLI is useful for most users, as they're not really using CLI for much of anything.
The importable library sounds good, but how many users will be using Java directly?

In my perfect world, what I'd really like is for this to be made into a [MIT App Inventor2](http://ai2.appinventor.mit.edu/) Extension that is built using [THIS Procedure](https://community.appinventor.mit.edu/t/how-can-i-make-an-app-inventor-extension-aix/2369/3).
The resulting extension(.aix) file can be monitized(or not) by adding it into [TaiFun's Extension Page](https://puravidaapps.com/extensions.php), OR, using the BTCToolbox.org page, OR, by using another web site, OR just given to the world for free.

If the extension is too much to handle, then the alternative is the JavaScript version that can be run via a tool in App Inventor that allow one to [run JavaScript directly from the app](https://appinventor.mit.edu/explore/ai2/webview-javascript).

Bitcoinjs.lib should have all the tools, BUT, I'm not exactly sure if the Bech32 module has been upgraded to the latest changes...if there are...not that it really matters to me because for the most part, I'm only going to rely on the BIP-49 address creation for my purposes.

I CAN also see a python version being useful too.

The BTCToolbox version was over the top...not sure what to do about it at this point. I should have had someone holding the rein's on me.  In hindsight, I was making it "too" cool, and I should know better.

Your thoughts?

**Comment by Septem151** [comment]
Just so I understand this correctly: you're wanting a program specifically targeted at End Users, and not for developers?

As far as the updated program flow you desire, it's basically the exact same as it currently is but with no "Q" option to quit, and combines the extended key and index into one question, is that correct?

**Comment by EAWF** [comment]
Sorry about my delay in replying,  I had to stop myself multiple times from "knee-jerking" and put my systems analyst hat back on and take time to think it all out.

### Q1:
- No, I believe that developers would be the only one's that would use this tool.

### Q2:
- Yes, using the bash shell, the invoking call would be "java -jar /path/to/Deriver-Tool.jar pub index", and the address would be returned to standard out.
- In this format, this call most likely would be made by a programming language utilizing an exec() function and your tool would be much more usable, because there is really no need to retrieve multiple addresses from the pub and incremented index. 
- Unless you can see something that I am missing?????

### NOTE:
After extensive thinking, as well as simplifying my needs, a BIP49 Address Generator method/function in an MIT App Inventor 2 .aix extension would be the most useful tool for me right now.

## Why BIP49 and not the others?
1; BIP32(xpub) addresses are long and increase the amount of miner fees required for a transaction to be included in the next block.
2. Bech32(zpub) addresses are still not searchable on all block explorers, and new technologies MAY require a protocol/address change in the future.
3. BIP49(ypub) addresses are:
- already searchable on all block explorers, and will continue to be so in the future.
- relatively inexpensive for miners fees
- fairly standard on most wallets. Yes, there are exceptions, but then someone else is welcome to rewrite if they feel the need. :smiley:
- focusing in on using only one address type simplifies:
  - the support issues.
  - reduces the size of the code to absolute minimum requirements to produce an address.

I hope that makes my case understandable?
